"""Add user_id to opportunity and order tables

Revision ID: a10a1adbbcc9
Revises: 
Create Date: 2025-09-21 00:27:29.950944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a10a1adbbcc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_opportunity_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('data_scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'own'"))
        batch_op.create_foreign_key('fk_user_role_id', 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key('fk_user_department_id', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_department_id', type_='foreignkey')
        batch_op.drop_constraint('fk_user_role_id', type_='foreignkey')
        batch_op.alter_column('data_scope',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'own'"))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('opportunity', schema=None) as batch_op:
        batch_op.drop_constraint('fk_opportunity_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###